[package]
name = "restate-storage-query-postgres"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
options_schema = ["dep:schemars"]

[dependencies]
restate-workspace-hack = { workspace = true }

restate-core = { workspace = true }
restate-errors = { workspace = true }
restate-partition-store = { workspace = true }
restate-storage-api = { workspace = true }
restate-storage-query-datafusion = { workspace = true }
restate-types = { workspace = true }

anyhow = { workspace = true }
async-trait = { workspace = true }
codederror = { workspace = true }
datafusion = { workspace = true }
futures = { workspace = true }
pgwire = { version = "0.28.0", default-features = false, features = ["server-api-ring"] }
prost = { workspace = true }
schemars = { workspace = true, optional = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }