[package]
name = "restate-metrics"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[dependencies]
metrics = { workspace = true }
workspace-hack = { version = "0.1", path = "../../workspace-hack" }
