[package]
name = "restate-utoipa"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license = "MIT"
publish = false

[features]
default = ["debug"]
debug = []

[dependencies]
restate-workspace-hack = { workspace = true }

serde = { workspace = true }
serde_json = { workspace = true }
indexmap = { workspace = true, features = ["serde"] }

[dev-dependencies]
restate-utoipa = { path = ".", features = ["debug"] }

assert-json-diff = "2"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(doc_cfg)'] }