[package]
name = "restate-timer"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[features]
default = []
options_schema = ["dep:schemars"]

[dependencies]
restate-workspace-hack = { workspace = true }

restate-types = { workspace = true }

ahash = "0.8.3"
pin-project = { workspace = true }
priority-queue = { workspace = true }
schemars = { workspace = true, optional = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
restate-test-util = { workspace = true }

futures-util = { workspace = true }
tracing-subscriber = { workspace = true }
test-log = { workspace = true }