[package]
name = "restate-encoding-derive"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false

[lib]
proc-macro = true

[dependencies]
quote = "1"
syn = { version = "2.0", features = ["full", "extra-traits"] }

restate-workspace-hack = { workspace = true }